i3, sxhkd, bin: Reintroduce i3 support

diff --git a/bin/wm-assign-desktop-to-monitor b/bin/wm-assign-desktop-to-monitor
--- a/bin/wm-assign-desktop-to-monitor
+++ b/bin/wm-assign-desktop-to-monitor
@@ -2,20 +2,44 @@
 #
 # Assigns a given desktop to the given monitor.
 
-wm-is-i3 && echo "ERROR Window manager not supported" && exit 1
-
 desktop="${1}"
 monitor="${2}"
 
+usage() {
+    echo "Usage: $(basename "${0}") DESKTOP MONITOR"
+    echo ""
+    echo "Options:"
+    echo "  DESKTOP: ID of the desktop to move"
+    echo "  MONITOR: Xrandr ID of the monitor that DESKTOP will be moved to"
+    echo ""
+    echo "Example:"
+    echo "  $(basename "${0}") 3 eDP-1"
+    echo "  Moves the third desktop to the monitor named eDP-1"
+    echo ""
+}
+
+bspwm_assign() {
+    bspc desktop "${desktop}" --to-monitor "${monitor}"
+}
+
+i3_assign() {
+    i3-msg '[workspace='"${desktop}"'] move workspace to output '"${monitor}"
+}
+
 if [ "x${desktop}" = "x" ]; then
-    echo "ERROR: Missing desktop variable"
+    echo "ERROR: Missing desktop argument"
+    usage
     exit 1
 fi
 
 if [ "x${monitor}" = "x" ]; then
-    echo "ERROR: Missing monitor variable"
+    echo "ERROR: Missing monitor argument"
+    usage
     exit 1
 fi
 
-bspc desktop "${desktop}" --to-monitor "${monitor}"
+wm-is-bspwm && bspwm_assign && exit 0
+wm-is-i3 && i3_assign && exit 0
+echo "ERROR: Unsupported window manager"
+exit 1
 
diff --git a/bin/wm-ensure-desktops b/bin/wm-ensure-desktops
--- a/bin/wm-ensure-desktops
+++ b/bin/wm-ensure-desktops
@@ -2,21 +2,28 @@
 #
 # Ensures the desired amount of desktops are available.
 
-wm-is-i3 && echo "ERROR Window manager not supported" && exit 1
-limit=4
-desktops="$(bspc query -D)"
-num_desktops="$(echo "${desktops}" | wc -l)"
+ensure_bspwm() {
+    limit=4
+    desktops="$(bspc query -D)"
+    num_desktops="$(echo "${desktops}" | wc -l)"
 
-if [ "${num_desktops}" -gt ${limit} ]; then
-   exit 0
-fi 
+    if [ "${num_desktops}" -gt ${limit} ]; then
+       exit 0
+    fi
 
-delta=$((limit - num_desktops))
-i=0
-while [ $i -lt $delta ]; do
-    bspc monitor -a "x${i}"
-    i=$((i+1))
-done
+    delta=$((limit - num_desktops))
+    i=0
+    while [ $i -lt $delta ]; do
+        bspc monitor -a "x${i}"
+        i=$((i+1))
+    done
+}
 
-wm-rename-desktops
+ensure_i3() {
+    limit=4
+}
 
+
+wm-is-bspwm && ensure_bspwm && wm-rename-desktops; exit 0
+wm-is-i3 && ensure_i3 && wm-rename-desktops; exit 0
+echo "ERROR Window manager not supported"; exit 1
diff --git a/bin/wm-singleton-desktops b/bin/wm-singleton-desktops
--- a/bin/wm-singleton-desktops
+++ b/bin/wm-singleton-desktops
@@ -2,18 +2,27 @@
 #
 # Ensures only one desktop is available.
 
-wm-is-i3 && echo "ERROR Window manager not supported" && exit 1
-limit=1
-desktops="$(bspc query -D)"
-num_desktops="$(echo "${desktops}" | wc -l)"
 
-if [ "${num_desktops}" -eq 1 ]; then
-    exit 0
-fi
+bspwm_singleton() {
+    limit=1
+    desktops="$(bspc query -D)"
+    num_desktops="$(echo "${desktops}" | wc -l)"
 
-delta=$((num_desktops - limit))
-while [ $delta -gt 0 ]; do
-    bspc desktop -r
-    delta=$((delta-1))
-done
+    if [ "${num_desktops}" -eq 1 ]; then
+        exit 0
+    fi
 
+    delta=$((num_desktops - limit))
+    while [ $delta -gt 0 ]; do
+        bspc desktop -r
+        delta=$((delta-1))
+    done
+}
+
+i3_singleton() {
+    "${HOME}/.config/i3/singleton.py"
+}
+
+wm-is-bspwm && bspwm_singleton && exit 0
+wm-is-i3 && i3_singleton && exit 0
+echo "ERROR: Window manager not supported" && exit 1
